/**
 * Writes pkg/brand/hex.generated.ts from src/shared/brandbook/brandbook.css.
 *
 * brandbook.css is the one file every visual value lives in. Two consumers
 * cannot read CSS — the notification email (inline styles in an HTML string)
 * and the theme-color meta tag — so they get hex copies of the brand palette,
 * written here.
 *
 * Runs automatically on `pnpm install`, before `next dev` and before
 * `next build`, so a colour is only ever edited in brandbook.css. The output is
 * gitignored: a generated file in git can go stale in a way nothing notices.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

// pnpm runs scripts from the package root, including postinstall.
const SOURCE = path.join(process.cwd(), 'src/shared/brandbook/brandbook.css');
const TARGET = path.join(process.cwd(), 'pkg/brand/hex.generated.ts');

const DECLARATION = /--color-brand-([a-z0-9-]+)\s*:\s*([^;]+);/g;
const HEX = /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i;

const toCamelCase = (name: string) =>
  name.replace(/-([a-z0-9])/g, (_, letter: string) => letter.toUpperCase());

function main() {
  const css = readFileSync(SOURCE, 'utf8');
  const colours = new Map<string, string>();

  for (const [, name = '', rawValue = ''] of css.matchAll(DECLARATION)) {
    const value = rawValue.trim();
    // Email clients do not reliably support oklch(), color-mix() or var(), so
    // a brand colour that is not a plain hex would silently break the email.
    // Fail the install/build instead, naming the token.
    if (!HEX.test(value)) {
      throw new Error(
        `--color-brand-${name} in brandbook.css is "${value}". Brand colours must be hex (e.g. #1d464a) — the notification email and the theme-color meta tag need a plain hex value.`,
      );
    }
    colours.set(toCamelCase(name), value.toLowerCase());
  }

  if (colours.size === 0) {
    throw new Error(
      `No --color-brand-* tokens found in ${SOURCE}. Has the brandbook moved? Update scripts/brand-tokens.ts.`,
    );
  }

  const body = [...colours].map(([key, value]) => `  ${key}: '${value}',`).join('\n');
  const output = `// GENERATED by scripts/brand-tokens.ts from src/shared/brandbook/brandbook.css.
// Do not edit — change the colour in brandbook.css; this file follows on the
// next install, dev start or build.

export const BRAND_HEX = {
${body}
} as const;
`;

  // Rewrite only on change, so an unchanged palette does not trigger a
  // rebuild or a hot reload.
  if (existsSync(TARGET) && readFileSync(TARGET, 'utf8') === output) return;

  mkdirSync(path.dirname(TARGET), { recursive: true });
  writeFileSync(TARGET, output);
  console.warn(
    `[brand-tokens] wrote ${path.relative(process.cwd(), TARGET)} (${colours.size} colours)`,
  );
}

main();
